### ISSUE TITLE
Few Issues we encounter 

### ISSUE THREAD

**Issue by DeviousCode** [ttgspeed/Sparc#4] opened 2015-10-10 14:46 UTC
Hey, Just found your rcon tool and loving it the only problems we found are 

Server Broadcast msgs - 
[10 Oct, 2015 | 07:31:21] RCon admin #0: (Global) Welcome to NAME A3: server.
Trigger admin call and starts flashing each time
turning off flash when admin call does not fix it

BattleEye Spam - 
[10 Oct, 2015 | 07:26:46] Could not connect to BE Master
[10 Oct, 2015 | 07:26:46] Update attempt failed
[10 Oct, 2015 | 07:29:02] Could not connect to BE Master
[10 Oct, 2015 | 07:29:02] Update attempt failed
[10 Oct, 2015 | 07:31:18] Failed to receive from BE Master (2)
[10 Oct, 2015 | 07:31:18] Update attempt failed
[10 Oct, 2015 | 07:33:34] Could not connect to BE Master
[10 Oct, 2015 | 07:33:35] Update attempt failed

Side Chat is not logged or showing in the Chat Tab and text color is black and not blue
[10 Oct, 2015 | 07:28:54](Side) Name: text text text
- this is my first  time writing a ticket for these so please forgive me if i did this wrong.

**Comment by ttgspeed** [comment] 2015-10-10 21:55
Server Broadcast msgs - Fixed, thank you

BattleEye Spam - That's an issue with BE on your server. It's reporting to RCON that it's unable to connect to the BE master servers. Most likely it's due to the BE servers being overloaded (as usual)

Side Chat issue - This is either a configuration issue on your server, or it's caused by the BE issue above. 
Correct text should look like the following:
[10 Oct, 2015 | 17:51:05] (Side) Name: text text text

If you don't see the side, that means it is not being reported properly by BE.

**Comment by DeviousCode** [comment] 2015-10-11 00:20
Just downloaded the new one and tested it out. its hard to explain  whats happen so i thought i show you lol. 
https://youtu.be/z-ZeyFrYDFg

i did Blur things out for my players protection. 

also in the video i highlighted that side chat shows but its in a black text and the Chat tab does not show side chat.

also you will see Rcon Admin is triggering the Flashing  and when players say admin it not registering

Keep up the great work =) 
Thanks DC

**Comment by ttgspeed** [comment] 2015-10-11 12:19
Ah, dumb bug on my end. I'll get it fixed!

**Comment by ttgspeed** [comment] 2015-10-11 17:44
Should be fixed with https://github.com/ttgspeed/Sparc/commit/c6aba130f752eaa88f7f4fdb7ed950cb7f107a93

**Closed as completed** 2015-10-19 01:12 UTC
Labels: bug
